apiVersion: v1
kind: Service
metadata:
  name: metrics-gateway
spec:
  type: NodePort
  selector:
    app: metrics-gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}